### ISSUE TITLE
กด Link ใน Nav bar แล้วไอคอนหาย

### ISSUE THREAD

**Issue by teerasej** [rhearnorth/spfarm#11]
กด link แล้วเปิดไปอีกหน้า ไอคอนมันหายไป ตรงนี้ไม่แน่ใจว่า มันมีอะไรไปขัดกับกลไกของ Rails หรือเปล่า เพราะทั้งหมดเป็น CSS และไม่ได้ใช้ JS

กดไปดูตัวอย่าง https://ibb.co/k311hc

**Comment by teerasej** [comment]
ปรากฎว่า การใช้ FontAwesome Icon แบบ SVG JS อาจจะมีการขัดกับกลไกการทำงานของ Rails
ตอนนี้สลับมาใช้เวอร์ชั่น CSS WebFont แทน แก้ปัญหาได้แล้ว

**Comment by rhearnorth** [comment]
เก่งมากเจ้าหมาเขียว
